### ISSUE TITLE
Code review notes

### ISSUE THREAD

**Issue by markerikson** [localjo/trivia-demo#1]
Hi, I'm a Redux maintainer.  A few quick thoughts after skimming through the code:

- First, given the current size of the app, Redux is definitely not _necessary_ here - this could easily be done with plain React state.  Nothing wrong with choosing to use Redux to get some practice with it, just pointing out that the data management isn't overly complex atm.
- The reducer logic is currently mutating the state.  In particular, `q.is_correct = correctBool === action.payload.answer;` is mutating `q`.  Per [the rules of immutable updates](https://redux.js.org/recipes/structuring-reducers/immutable-update-patterns), you need to copy _every_ level of nesting that is being updated.
- Third, I'd strongly suggest using [our new official Redux Toolkit package](https://redux-toolkit.js.org/), which contains utilities to simplify your Redux logic. In this case, it would allow you to remove the `action-types.ts` and `actions/index.ts` files entirely, because it can generate those for you automatically based on your reducers:

```ts
const initialState: IAppState = {
  status: IStatus.INIT,
  questions: [],
};

const questionsSlice = createSlice({
    name: "questions",
    initialState,
    reducers: {
        setStatus(state, action: PayloadAction<IStatus>) {
            state.status = action.payload;
            if(action.payload === IStatus.INIT) {
                state.questions = [];
            }
        },
        addQuestions(state, action: PayloadAction<IQuestion[]>) {
            state.questions = action.payload;
        },
        submitAnswer(state, action: PayloadAction<{question: IQuestion, answer: string}>) {
            const matchingQuestion = state.questions.find(q => q.question === action.payload.question);
            if(matchingQuestion && matchingQuestion.type === 'boolean') {
                const {correct_answer} = matchingQuestion;
                const correctBool = /true/i.test(correct_answer);
                // Can "mutate" the state here because createSlice uses Immer inside
                q.is_correct = correctBool;
            }
            else {
				q.is_correct = false;
            }
        }
    }
})

export const {setStatus, addQuestions, submitAnswer} = questionsSlice.actions;
export default questionsSlice.reducer;
```

**Comment by localjo** [comment]
Thanks @markerikson 👍 (fellow Ohioan here, by the way!)

I appreciate your feedback! I implemented your suggestions and added Redux Toolkit in d15a0983843eade99aafcefa82ce5461b6286ad9
